name: Build Octave Builder container images

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_octave:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        version: [4, 5, 6, 8]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build-octave-${{ matrix.version }}.docker
          build-args: |
            OCTAVE_VERSION=${{ matrix.version }}
          push: true
          tags: |
            gnuoctave/octave-build:${{ matrix.version }}
            ghcr.io/gnu-octave/octave-build:${{ matrix.version }}
